services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    env_file:
      - ".env"
    ports:
      - "5007:${PORT}"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app:app --workers ${WORKER} --host ${HOST} --port ${PORT} --log-level debug --access-log"
    restart: always
    volumes:
      - ".:/app:ro"
    depends_on:
      - db
  
  db:
    image: postgres:14-bookworm
    container_name: pedantic_mayer
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432:5432"